language: node_js
node_js:
- 9
services:
- redis-server
before_script:
- npm install -g gulp-cli
script:
- gulp
- npm run coverage
cache:
  directories:
  - node_modules
env:
  global:
  - secure: YkmOeS8jzNB9cyU+z5PnM8Bn+zdnAAwudRxPRgXprDV4hLRG4Wi2BC5Je5dmoDRIrjS7+P7dnm2KwXaep3Suso4LmANQQgBv80W8AgAuSCtGXEA8eN8J5z0rmEl3pZiDX3CA13eCgz6iQ5654YsE/bLSujKygx72AX7JHCdf/c+l0hmaz1eqAhFzionQ1cotaQe++X3bYlflwSAUeZ1/UjRLDgK4G1klEMrZESVIN6WrHMxe+NjbdzYLOCEJ470wNe60ZJmd8PBEi4kFulybVlWpkfH6f6wgyH/YLEhbi1JlZ2oNVwVNJ+8h9gN6y6Us78G8LzI04yN8i6ouJU+qNMDvRffUOBM4Js7G0C1upEM45+AFWsEA7pbdtHGO0gAs4n+2rqzub/exMIrlVjAikFqUs+/oLX2zBnoiqgTShbidIMF9cMUmirAi08JLjLGtkLvmRXP0iQcsVWSQ65HnpnBqNhxu0AobYsDcSUMZAHdv5Tg2uMI0Iv/o1fk03MLevKzqlPdzv4nC6jlEi20sdn8mcUO8JL2k+4BJVCj/OTerHlJleESagQBHpEWoq+GisGIMImFIFU5XSwuqhpRwV9HeRZLXLvF9XEHzj2UJpuKaTRTZZvlxg6Rsbk8yus83pTTDRMRJQpFp5gVSOf532dXqtdsihEmsMdeToYtc8VA=
