language: node_js
node_js:
- 10
services:
- redis-server
before_script:
- npm install -g gulp-cli gulp@4
script:
- gulp
- npm run coverage
branches:
  only:
  - master
  - develop
cache:
  directories:
  - node_modules
env:
  global:
    secure: sHNGm2BqpKRq6dA+wC26H33tsYAygbiK32jzJV2H+BfjOijV+eZ9XS63w2rNnN7nHRgBBsEw8vcoG039M6RreeGxx8oJ41be6nBZtsISD0ONGM6K6jXpbK017utJu2HmBo2OZM0GfXI+zqMvQ2OR1a9hY1KA5l4zclBJE89CkKUffMdb3hNwNsEszTy16+gHIeR1YR5qa8OonTwi68YS5vK7FCv/6Hrsq/kHt+NjSA4mQaNBv3elOfPUCQpTXoTXCJEinpFtXKiwwox4U5Ea/6rJh0Mc6tp6BuIc7DXSzlfxyJZ5I5MUz/9D99Xrs7855zij0zSQ/IzsjYmPUepynHT+/UNodGndJ4eaoxE5KnvcETykUw5M2qWsvaB+MkSb7QeiOAGA6G3VFDx9aXM/YYtD2lm3FCwZ8h007CUZTwToZtitS25GNz8O4I3LNce00WKLTkM0vwVNi3oqHfVRefCpHbf6rqTxzQcoPFvMlctUiCVMajlETpkXoCyxr0i4F6AXEf9D3dFx/+arHXHYOjtPAmW2bS4mUojXlzJnz8a0l5F1eKwS67k5L8DkgCt9gb4cJjYJcWUg9sxbEeBxqa7w9prl4nBZBpziYYNINtqBUT6WZbxO4Tbxn0agDvyjlL7dfWzOkW4FKqKze90uLkew6eSKOGsdqswabM9RZlc=
notifications:
  slack:
    secure: RCvgB44XeUq7/4s+OuCxzWfHmWmXpeqC0894P3Dxuc25haVhJKWuMc+G18+7aQlxF9+ZXGzNBSUTWRjVRGn7c+MZJ4fGu63tG3tfj8khLH3GsHxJYjUfYw0sX5HpmeJ3LXqKMJb05xalwqve2wfdDbwdiOiWOigQMXoDPq28NGj5xJLa17vdQ8qI/m8MMe5AoJVS/AnRr6UJ7txEla7i/5zPMret8/4iCaMGZaY5ywilppiSWPdERa9EjMsHGwN1h2sw5lA0PwVBAzZ1EeKLQfLan4jVHQlIDrg6Kv5qZlAjrpK+jDGwBfvRocx7NmVfmzuBWhp5BNgjXzgwvpLZHMRrFLspNt4KewbP8gbnLgL13LvN7F/zhNgwBWopdB70+SwqdooGDfdxcYls3MSdRlwUq0QHSxxm2V+u3TS2l15Q2CGwHPlvYoDjpPgpi222/5sOZoege5DFi4v3ZgoTzSdSz5TbDVk6ylIWlQc78TaK2Fx6c9+K7fCld4OWH8AuYYH32tGazNCti4yyYtncqOD9n0XkT2WqmHI9ChZ/TpNBAXFh9obhgzOwzP8quK26ZyZWQHUOaTudIJl6H6O+a4yI47UZgYq//vKe68jQ52LOqBHUbsh1T2vW71WNOshAMeCok6ls2fac/LpRv+UVg+IWpjp3m0rKVoXToKdfVLw=
deploy:
- provider: npm
  api_key:
    secure: NH1sFjL1NQ5tokfSkvbLYXs4hKE8gejXSekyoMZoylDhvZwYvgKFXnaeZ97phMIOxeNwOhCK7sSmcBNwDkaXla+VJ7q00ZhQcyZcjdhhFbJTS7saY6CyR6A4RMINdZXWl+/+EKnk+QMSsdr2hJlEPUcmuu6BpsYz2z2yPAhQNQ0+Shupf4a9HtltdDcSDzKy/hGjRGGwe9Y6539NSo3poJozjbFCDfpupv0lLAfK+SKjhvoSo84Jlp5NJ3Rv/eN4HTagFEFQF1w++62WYeKiaEvdF+0+6FC4diS5LFpHIiCoG6LbH8OFoeIvgC2PIcWhtsYY+82oZOkX2ojNTmreUHfSq5H/0zcE5kGk3+wK4kCSE0a/+GX/BQB94+ePK2oHG+76kFamuR0hz1b8cA9qqzyn8S6jMZTFHLxcVLE7ibmstWFdfILzpmLYlHye0S2QnsrcdP5nfMIGtRhbB9N2eeKADOmQVxCBGLBiYTELraXf1ccEojTkcxsjfHQju7VoUvoggfG78t7VwBT4LZDLiBV0N1ExgCp2H5dGM+ZD/EWhlm5fttx8D+MLbmS83QQqMqmSf7/tQQiWu5XzzBLDNmbdp0z4L7JUD43fHvIJl310o8F9tPTNzNjttjW4JMPhdogkvvX/n2POvqLuRdQ7bF//bKrDojKeNN+quz1XKP4=
  email:
    secure: ZEheqkHYcBugmPiIGSsEwiubjBmVCREObpkjwWyfooEbYlirallF/EP8/8drkuHJaVBWyd53vBhPjvB0sBPw4B2zFT4/nyzYsDZIcyD76ushJA8S33xFbZEwupEsMTSLGdACv4ESwWEdHfAKu83fkHntfQm+MsO0vk6G8LS+H91aXExzD/PNb8h/lbTR7LkdGBptR/l/xl60SEAU7hgcYXiZ3OJESqqRKZSZd24S8lkN8+8S2XDwlQngTKLYwJDAuaQzmW88j92eWOuULCd9W2cZNGrsmk4d5bOCyz/X71yabc0tZP3ONENR3R0T6bgGO6WvkfMZqGemunDU2ziijWHqq/NDlbrJzUGr35w1EpV3naq7+UMvBHEBVXMDH9WZfjWHiyV5+aFpOGy3028fOjCPpl+IcgYhcqlk0bndjVzO2cML42/v3iTOYE/oFJtbOZR9DWaTdUfT1r1tkH4xEIUdCZjxSrpoPOPFGelqh9cw/3R8WI/kcQNUH9DKQggQM+rGVfMIVI0Ua7ckeSSt9IJwJsmsGVkRQUo5MaXygmD/asMWWPIhOckW0++G6+vsSqiszT7n1pqttjHsBq9PBZARubfRLvoW7FnHRPYptDG0XcdCTfmLSF0vGjr007tALFv5dz3WaNslNh3reUsGCEq5VBXpeWjevpIU7LcfTGc=
  on:
    branch: master
