language: node_js
node_js:
- node
services:
- redis-server
before_script:
- npm install -g gulp-cli
script:
- gulp
- npm run coverage
cache:
  directories:
  - node_modules
env:
  global:
    secure: JRodOFRcrKKk16nPmETiq2Y3j31mjzNszieI5QxWSzkWfXK8VXqUCpc5YwuVZs2kQ6N4bbWkf3koNJ59Wm9fqptNpy7MN4ceqPgJGgt9xqNhcVfAK9Pcnk7prXHMxti2eOrdezITenLhVNfHTDJEZxafy0Z7JuM8qERFuUc3vT0l92GXAfnpg9fEQqIcrmZnfrP4mVniUzrcfeMID7nBIMMk17C9hopfaHJIcY52WAF5YeXJWWjYJia+uZtE5Q60lEzuWsE1BT4So50piGZbwtb6UYlNtGzZVaeUsZdXDHw5Qf6CKMHzj8R8buoOGu+0p7c7W/tDwXMBOJffMfR0xg+7dHqAsP4kTUc2KbJa5Q9H4pxyqEqCwkPZpfQu2hXMtheREwbZ/TVWBDIG7aUC4Cm+4hEyyTZNl89guunWo81YycQWJ/RzSxH0bRgXKEBqKZ2WAI/Ni5ZJmAouiFSuB00kOjPc6EOMZRDsOtba0FmLs2L+z3ZnDsGsuNDmdr/VdmUAHZDOWLnDvFX3j6AWyMN3jhp6F0ZWHHgeuvtCAWttFOEK+kGgjJC/6HMIpmv8DzOym12u5OBT/nfrnUrPauthOktj8OOflv3UCkv0P/OkVHqS3sJ0gE6iX2zG7SyXWXvgFe6XhpTvtwyp6/PYuLY0ozrQ1u6u1Nf8B4Un8Io=
